### ISSUE TITLE
can you suggest me how can I solve this line 

### ISSUE THREAD

**Issue by 23bca280** [vtcbca/internal-exam-23bca280#2]
![image](https://github.com/user-attachments/assets/5853b409-4efd-4f9c-8ccc-257300b7c23e)
please suggest me how to solve this (how to print small or largest word of file ?)

**Comment by 23bca274** [comment]
> ![image](https://github.com/user-attachments/assets/5853b409-4efd-4f9c-8ccc-257300b7c23e)
> please suggest me how to solve this (how to print small or largest word of file ?)


Do as following :- 

1. Read the content of the file then split the content into words with the use of split().

2. Fine the smallest and largest words by length and then print it. 

Ex :- small_words = min(words, key=len)
         large_words = max(words, key=len) 

I hope this may help you.

@23bca280

**Comment by 23bca280** [comment]
> > ![image](https://private-user-images.githubusercontent.com/177500376/367160408-5853b409-4efd-4f9c-8ccc-257300b7c23e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MDYzODYsIm5iZiI6MTcyNjgwNjA4NiwicGF0aCI6Ii8xNzc1MDAzNzYvMzY3MTYwNDA4LTU4NTNiNDA5LTRlZmQtNGY5Yy04Y2NjLTI1NzMwMGI3YzIzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQwNDIxMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZTBjZmRmNzE5NjJiYzBiN2Y0ZGZjYzkwYjU1MmU3ODE3NjlmN2NjN2QyNjVjYzdjNDQwMjk4YzExNjk5Zjg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.aj3gTmn7dMWCblko619vQ7D8BPXRZD-f773G0WAcxvc)
> > please suggest me how to solve this (how to print small or largest word of file ?)
> 
> Do as following :-
> 
> 1. Read the content of the file then split the content into words with the use of split().
> 2. Fine the smallest and largest words by length and then print it.
> 
> Ex :- small_words = min(words, key=len)
 large_words = max(words, key=len)
> 
> I hope this may help you.
> 
> @23bca280
I appreciate your efforts 
thank you for help!!
